### ISSUE TITLE
Cloud9 Primer

### ISSUE THREAD

**Issue by lizroth** [aws-samples/busy-engineers-document-bucket#120]
As a workshop student I would like a quick little introductory thing to use Cloud9.

Link to a cheat sheet if available or write a quick one.

Including cool Command-P things.

**Comment by deepikavasudevan** [comment]
Cloud9 source: https://docs.c9.io/docs/navigate
Tutorial: https://docs.aws.amazon.com/cloud9/latest/user-guide/tutorial.html

**Comment by lizroth** [comment]
Keybindings reference: https://docs.c9.io/docs/keybindings

**Comment by lizroth** [comment]
Write up doc viewing mechanism in primer: https://docs.aws.amazon.com/cloud9/latest/user-guide/app-preview.html#app-preview-preview-app
