### ISSUE TITLE
Minor templating issues.

### ISSUE THREAD

**Issue by lizroth** [aws-samples/busy-engineers-document-bucket#121]
Some of the color choices have some usability issues:

* Dark grey on light grey background in code blocks is hard to read
* Red text on yellow highlight is hard to read
* Inline blocks have too dark grey background for how contrasty the text is

Rendering error:

* Highlights do not extend all the way

**Comment by johnwalker** [comment]
The scroll bar for examples is maybe 3 or 4 pixels tall. It looks nice, but it's hard to access from a touchpad.

**Comment by ttjsu-aws** [comment]
Copy to clipboard icon doesn’t copy the highlighted content in yellow and copies extra lines of code. 

Example: 
```
// Edit Api.java
public PointerItem store(byte[] data, Map<String, String> context) {
    // ADD-ESDK-START: Add Encryption to store
    CryptoResult<byte[], KmsMasterKey> encryptedMessage = awsEncryptionSdk.encryptData(mkp, data);
    DocumentBundle bundle =
        DocumentBundle.fromDataAndContext(encryptedMessage.getResult(), context);
    writeItem(bundle.getPointer());
    ...
```
instead of 
```
CryptoResult<byte[], KmsMasterKey> encryptedMessage = awsEncryptionSdk.encryptData(mkp, data);
```
