### ISSUE TITLE
make bootstrap fills the disk

### ISSUE THREAD

**Issue by mattsb42-aws** [aws-samples/busy-engineers-document-bucket#173]
Following the setup instructions[1], `make bootstrap` fails partway through because it filled up the local disk.

[1] https://document-bucket.awssecworkshops.com/getting-started/

**Comment by mattsb42-aws** [comment]
fixed by #167

**Comment by lizroth** [comment]
We should reopen this -- this probably should 1) not run automatically in bootstrap and 2) be relocated to a different place.

**Comment by lizroth** [comment]
Also the permissions seem to not be working to run the resize from within Cloud9 anymore.

**Comment by lizroth** [comment]
https://github.com/aws-samples/busy-engineers-document-bucket/issues/179

**Comment by lizroth** [comment]
Maybe we should consider not bootstrapping everything for now?
