### ISSUE TITLE
Java: incorrect dependency version

### ISSUE THREAD

**Issue by rndsite** [aws-samples/busy-engineers-document-bucket#249]
Java code is broken and report the following error
```
|  Exception java.lang.NoSuchMethodError: 'com.amazonaws.services.kms.model.DecryptRequest com.amazonaws.services.kms.model.DecryptRequest.withKeyId(java.lang.String)'
|        at KmsMasterKey.decryptDataKey (KmsMasterKey.java:162)
|        at KmsMasterKeyProvider.decryptDataKey (KmsMasterKeyProvider.java:493)
|        at DefaultCryptoMaterialsManager.decryptMaterials (DefaultCryptoMaterialsManager.java:117)
|        at DecryptionHandler.readHeaderFields (DecryptionHandler.java:617)
|        at DecryptionHandler.<init> (DecryptionHandler.java:109)
|        at DecryptionHandler.create (DecryptionHandler.java:300)
|        at AwsCrypto.decryptData (AwsCrypto.java:515)
|        at AwsCrypto.decryptData (AwsCrypto.java:502)
|        at AwsCrypto.decryptData (AwsCrypto.java:475)
|        at Api.retrieve (Api.java:271)
|        at Api.retrieve (Api.java:234)
|        at (#6:2)
```
Suspect it is because of the incorrect dependency version.

`pom.xml` specifies to use AWS Encryption SDK version 2.2.0 with AWS Java SDK version 1.11.675. AWS Java SDK version 1.11.675 does not have `withKeyId` method in `DecryptRequest`.

According to the official AWS Encryption SDK, version 2.2.0 specifies to use AWS Java SDK version 1.11.704.

Therefore, suggest using 1.11.704 for AWS Java SDK.

**Comment by lavaleri** [comment]
Hi @rndsite,

Thanks for cutting this issue! We have updated the SDK version to v1.12.255 and the workshop should be working again. I'll close this issue out, but please feel free to open a new issue if you run into more issues.
