### ISSUE TITLE
Do all the bootstrap in the Cloud9 init?

### ISSUE THREAD

**Issue by lizroth** [aws-samples/busy-engineers-document-bucket#36]
Take @seebees forthcoming Makefile magic and wire it in to have Cloud9 just do the thing as they launch the IDE?

**Comment by seebees** [comment]
Also the project.settings file has python information:

```
  "python": {
        "@path": "/usr/local/lib/python3.4/dist-packages:/usr/local/lib/python3.5/dist-packages"
    }
```

**Comment by lizroth** [comment]
Need to make sure that the Cloud9 instance has enough disk at init time to actually finish the bootstrap. (Blocked by https://github.com/aws-samples/busy-engineers-document-bucket/issues/179 )
