### ISSUE TITLE
Add a background page to the instructions for foundational concepts.

### ISSUE THREAD

**Issue by lizroth** [aws-samples/busy-engineers-document-bucket#64]
As a workshop student following along at home or who would like a refresher while I work, I would like to have a documentation page that has background information on definitions and interactions.

Things like

* What is a data key?
* What is a customer master key?
* What is encryption context?

Etc.

**Comment by jangellataws** [comment]
AWS Key Management Service (AWS KMS)
AWS Encryption SDK
AWS Cloud9
Amazon S3
Amazon DynamoDB
Customer Master Key (CMK)
Unique Identifier (UID)
Encryption Context
Document Bundle

**Comment by lizroth** [comment]
Random number generation / entropy
Cryptographic details whitepaper link?
