### ISSUE TITLE
Make pointer comments clearer.

### ISSUE THREAD

**Issue by lizroth** [aws-samples/busy-engineers-document-bucket#66]
As a workshop student, making comments like `# ADD-ESDK-START` more explicit like `# ADD-ESDK-START: Changes go here` would be helpful.

**Comment by peterchung-git** [comment]
Leaving an empty line after the comment would be helpful as well.  Sometimes, there are other comments/code right after "# ADD-ESDK-START", and it is not immediately clear whether my new code goes immediately after the comment OR after the block of which "# ADD-ESDK-START" is part of.
