### ISSUE TITLE
AWS SDK for Javascript and regions

### ISSUE THREAD

**Issue by seebees** [aws-samples/busy-engineers-document-bucket#75]
The AWS SDK for Javascript seem to have odd region resolution.
The region exists in `~/.aws/credentials` in Cloud9 IDE.
But the SDK does not pick it up unless `AWS_SDK_LOAD_CONFIG` is set.
However if that is set,
then the SDK does not pick up the credentials from `~/.aws/credentials`.

Either the AWS SDK or the Cloud9 environment should be made to "just work"

**Comment by lizroth** [comment]
This might be patched but not in a way we're totally satisfied with. Flagging as bug so that we follow up to make sure it's resolved before our next presentation.
